Fix #4
* Feature request - add satured add: adds

* Change saturated add (adds) domain from NxN to RxR

* Fix curly braces issue

* Add required named args for the formatted string in platform_x86 adds(...)

* Feature request - add satured substraction: subs

* Fix code generation error in platform_cpu.py adds function

* Add missing <climits>/<limits.h> include for INT_MIN/INT_MAX in platform_cpu.py

* In platform_cpu: Add missing semicolon in subs() and generate the corresponding MIN/MAX macro string for the given parameter type

* Fix typo in platform_cpu adds(typ) ValueError exception message

* Remove not needed semicolon in def enum(l)

* Move the limits dictionary from platform_cpu.py to common.py since limits is needed in gen_tests.py as well to test adds and subs functions

* For backup

* Add tests for adds - in progress (for backup). Tests for unsigned are failing

* Python egg/gen_tests.py - function gen_adds(...): add missing arg 'opts' which should be passed to common.open_utf8

* Python egg/platform_x86.py - functions adds(...): fix missing ';'

* adds function - python platform_cpu.py: remove unnecessary checks for unsigned types + refacto

* adds function - python platform_cpu.py: factorize out some code using helper functions

* adds function - python platform_cpu.py: better naming

* subs function - python platform_cpu.py: deal with unsigned case

* adds/subs functions - python platform_cpu.py: fix missing curly braces around 'typ' + bug in ValueError message

* adds function - python platfom_arm.py: adds(ftypes) - remove type in return statement

* adds function - python platform_x86.py: rewrite implementation + add comments

* adds/subs functions: - python platform_cpu.py: replace 'cpu' hard coded string + other syntax cleaning

* adds function - python platform_x86.py - fix: replace dict by tuple + add TODO: add simplified implem for unsigned + fix: str interpolate max_c_macro

* adds/subs functions - python platform_x86.py: adds: split format args over several lines - subs: implement

* adds function - python platform_x86.py - implementation for unsigned > 16 bits

* subs function - python platform_x86.py: cleanup

* adds function - python platform_x86.py: add to_logical.h include for avx512

* adds function - python platform_x86.py - add missing type for ires

* adds function - python platform_x86.py - add missing ''.format(**fmtspec)

* Subs(Operator) - python operators.py - fix typo in full_name + desc: substraction --> subtraction

* adds function - python platform_x86.py - add saturated sum provided as intrinsic instruction for i8, i16, u8, u16

* subs function - python platform_x86.py - add saturated subtraction provided as intrinsic instruction for i8, i16, u8, u16

* adds/subs functions - python platform_x86.py: add helper function adds_subs_intrinsic_instructions_i8_i16_u8_u16(...) to factorize out some common code between adds ans subs

* adds function tests - python gen_tests.py - Use helper functions to cover tests cases for floats and signed/unsigned integers (in progress) + remove trailing whitespaces in the file

* adds function - python platform_cpu.py - remove trailing whitespaces

* adds function tests - python gen_tests.py - Enhance adds tests for signed types (in progress)

* adds function tests - python gen_tests.py - style: use ++ii rather than ii++ in for-loop increment

* adds function tests - python gen_tests.py - test_adds_signed_underflow(typ, limit): enhance implementation

* adds function tests - python gen_tests.py - better naming: flip_sign() --> random_sign_flip()

* adds function tests - python gen_tests.py - better naming - add 'adds_signed' to helper functions: is_[overflow/underflow], is_neither_overflow_nor_underflow

* adds function tests - python gen_tests.py - clean adds_signed_is_overflow(...) and adds_signed_is_underflow(...) implementations

* adds function tests - python gen_tests.py - test_adds_signed_all_cases(...): replace while-loop by for-loop

* adds function tests - python gen_tests.py - style: add line separator with gen_adds as comment

* adds function tests - python gen_tests.py - test_adds_signed_overflow(typ, limit): enhance implementation

* adds function tests - python gen_tests.py - fix temp Not implemented: return as a comment

* adds function tests - python gen_tests.py - helpers - add: aligned_alloc_error(), adds_subs_check_case(), zero_out_arrays(typ) + move random_sign_flip()

* adds function tests - python gen_tests.py - update test_adds_signed(): add zero_out_arrays(...) and use CHECK_CASE(...)

* adds function tests - python gen_tests.py - update gen_adds(...) following addition of aligned_alloc_error(), adds_subs_check_case(), zero_out_array(typ)

* adds function tests - python gen_tests.py - add sections comments

* adds function tests - python gen_tests.py - replace comp_function(...) by equal(...) + couple fixes

* adds function tests - python gen_tests.py - add support for cxx_base and cxx_adv

* adds function tests - python gen_tests.py - cleanup: remove outdated comment

* adds function tests - python gen_tests.py - add tests for unsigned types (in progress) + cleanup

* adds function tests - python gen_tests.py - test_adds_signed_all_cases(...): remove erroneous hard coded INT_MAX/INT_MIN

* adds function tests - python gen_tests.py - add test_adds_unsigned_all_cases(...) + related update

* adds function tests - python gen_tests.py - factor tests given type getter out from gen_adds(...)

* adds function tests - python gen_tests.py - fix erroneous curly brace in compare_expected_vs_computed(...) + cleanup

* adds function tests - python gen_tests.py - do not add irrelevant tests for floats

* adds function tests - python gen_tests.py - better naming + fix get_tests_cases_for_unsigned_types(...)

* adds function tests - python gen_tests.py - better naming: compute_values_given_language(...) --> compute_adds_values_given_language(...)

* subs function - python platform_cpu.py - remove unnecessary min (0) in check_uderflow for unsigned + add cast to type for zero

* subs function - python platform_x86.py - replace erroneous UINT_MIN by (typ)(min_) ie (typ)(0)

* adds function tests - python gen_tests.py - return int from equal, overflow/underflow/neither overflow nor underflow helpers

* subs function tests - python gen_tests.py - add support for subs in 'General tests helpers for adds/subs' section

* adds function tests - python gen_tests.py - better naming - integer is implicit

* adds function tests - python gen_tests.py - rename get_tests_cases ... --> get_adds_tests_cases following the addition of subs tests cases

* subs function tests - python gen_tests.py - implementation in progress of subs tests

* adds function tests - python gen_tests.py - test_adds_overflow(...): fix comment

* subs function tests - python gen_tests.py - fix C functions names: replace erroneous adds by subs

* adds/subs functions tests - python gen_tests.py - make test_signed_neither_overflow_nor_underflow(...) and test_signed_all_cases(...) generic to test both adds and subs operators and move into 'General tests helpers for adds/subs' section

* adds function tests - python gen_tests.py - fix CHECK_CASE msg in tests_adds_signed()

* subs function tests - python gen_tests.py - make subs_signed_is_neither_overflow_nor_underflow(typ) function body coherent with function name

* subs function tests - python gen_tests.py - implement subs operator tests for signed types

* subs function tests - python gen_tests.py - fix section title

* subs function tests - python gen_tests.py - implement test_subs_unsigned_underflow(...), test_subs_unsigned_no_underflow(...), tests_subs_unsigned()

* subs function tests - python gen_tests.py - implement test_subs_unsigned_all_cases(...)

* subs function tests - python gen_tests.py - implement get_subs_tests_cases_for_unsigned_types(...) + update get_subs_tests_cases_given_type(typ)

* adds/subs functions tests - python gen_tests.py - test for equality between expected and computed values at each chunk step + update and rename compute_adds_or_subs_values_given_language(...) --> compute_op_given_language(...)

* Update Agenium Scale Copyright year 2019 --> 2020

* adds/subs functions tests - python gen_tests.py - update tests cases return type

* adds/subs functions tests - python gen_tests.py - add missing c/cpp function helpers + fix c/cpp function name error: subs_is_overflow(...) --> subs_signed_is_overflow(...)

* subs function tests - python gen_tests.py - test_subs_signed_overflow(...): protect against (... % 0)

* adds/subs functions tests - python gen_tests.py - change comments' style C++ --> C89

* adds/subs functions tests - python gen_tests.py - make C/C++ tests code C89 compliant

* adds - platform_x86: remove unnecessary max(in0, in1) computation to detect overflow for unsigned types

* adds - platform_x86 - fix compilation error: u_{num_bits} --> u{num_bits}

* adds - platform_x86 - fix use max limits for all integer signed types

* adds - platform_x86 - fix missing curly brace: '{' --> '{{'

* adds/subs functions tests - python gen_tests.py - explicitly cast to target type the type resulting from (rand() % ...)

* subs - platform_x86 - fix function name error: nsimd_{simd_ext}_set1_{typ}(({typ}){min_}) --> nsimd_set1_{simd_ext}_{typ}(({typ}){min_})

* adds/subs functions tests - python gen_tests.py - fix missing explicit casts generating warnings + assignment error

* adds/subs functions tests - python gen_tests.py - fix missing explicit casts generating warnings

* adds/subs functions tests - python gen_tests.py - better args naming for equal(...) function

* subs - platform_x86 - fix and simplify subs for unsigned types

* adds/subs functions tests - python gen_tests.py - test_signed_all_cases(...): fix explicit casts generating warnings

* adds/subs functions tests - python gen_tests.py - fix for-loop init declaration not allowed in C89

* adds - platform_x86 - fix adds for integer signed types (32/64 bits)

* adds - platform_x86 - use intrinsic blendv for all possible extensions (not avail in avx512 and sse2)

* platform_x86.py - remove trailing whitespaces

* adds/subs functions tests - python gen_tests.py - fix missing escape character for double quotes

* adds - platform_x86 - remove f strings not supported prior to python 3.6

* adds/subs functions tests - python gen_tests.py - remove f strings not supported prior to python 3.6

* subs - platform_arm: fix missing ';' and return statement

* subs - platform_arm: remove trailing whitespaces

* subs - platform_arm use intrinsics for integer types rather than nsimd_adds...(a, -b)

* adds/subs: generate functions for floats

* adds/subs tests: do not generate tests for floats as adds/subs(floats) just wrap add/sub(floats)

* adds - platform_arm.py: remove unnecessary include

* Remove trailing whitespaces

* include/nsimd/nsimd.h - format using clang-format (according to the command used in egg/common.py - def clang-format(...): clang-format -style="{ Standard: Cpp03 }" -i include/nsimd/nsimd.h

* include/nsimd/nsimd.h - add typedefs for integers limits (in progress)

* egg/common.py: use NSIMD macros for integers limits implemented in nsimd.h

* include/nsimd/nsimd.h - typedefs for integers limits (in progress): fix missing upcasts

* include/nsimd/nsimd.h - NSIMD_I64_MAX: use bit shifts rather than a litteral to increase portability safety

* adds/subs: fix/clean #include statements

* adds/subs - operators.py: remove bench against std/mipp

* Trim trailing whitespace